---
name: "Build All"
on:
  push:
    paths:
      - .github/workflows/build_all.yml
  pull_request:
    paths:
      - .github/workflows/build_all.yml

jobs:
  build_robotmk:
    uses: SoloJacobs/test_ci/.github/workflows/robotmk.yml@main
  build_rcc:
    uses: SoloJacobs/test_ci/.github/workflows/rcc.yml@main
  build_test:
    uses: SoloJacobs/test_ci/.github/workflows/test.yml@main
  download:
    runs-on: ubuntu-latest
    needs: [build_test, build_robotmk, build_rcc]
    steps:
      - name: "Download All"
        uses: actions/download-artifact@v3
