---
name: "Build All"
on:
  push:
    paths:
    - .github/workflows/build_all.yml
  pull_request:
    paths:
    - .github/workflows/build_all.yml

jobs:
  build_robotmk:
    uses:  octo-org/example-repo/.github/workflows/called-workflow.yml@main
