---
name: "Build All"
on:
  push:
    paths:
      - .github/workflows/build_all.yml
  pull_request:
    paths:
      - .github/workflows/build_all.yml

jobs:
  build_release:
    uses: elabit/robotmk/.github/workflows/release.yaml@dev/sol/artifacts_II
  release:
    runs-on: ubuntu-latest
    needs: [build_release]
    steps:
      - name: "Download All"
        uses: actions/download-artifact@v3

      - name: "Show Available Artifacts"
        run: find . -type f

      - name: "Update Release"
        uses: ncipollo/release-action@v1.13.0
        with:
          name: "Daily Build"
          allowUpdates: true
          artifacts: "executables.zip"
          replacesArtifacts: true
          removeArtifacts: true
          prerelease: true
          artifactErrorsFailBuild: true
          updateOnlyUnreleased: true
          makeLatest: false
