---
name: "Build All"
on:
  push:
    paths:
    - .github/workflows/build_all.yml
  pull_request:
    paths:
    - .github/workflows/build_all.yml

jobs:
  build_robotmk:
    uses: SoloJacobs/test_ci/.github/workflows/robotmk.yml@v1
