---
name: "Build All"
on:
  push:
    paths:
      - .github/workflows/build_all.yml
  pull_request:
    paths:
      - .github/workflows/build_all.yml

jobs:
  build_robotmk:
    uses: SoloJacobs/test_ci/.github/workflows/robotmk.yml@main
  build_rcc:
    uses: SoloJacobs/test_ci/.github/workflows/rcc.yml@main
  build_test:
    uses: SoloJacobs/test_ci/.github/workflows/test.yml@main
  download:
    runs-on: ubuntu-latest
    needs: [build_test, build_rcc, build_robotmk]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: robotmk.exe
      - uses: actions/download-artifact@v3
        with:
          name: robotmk_collector.ps1
