---
name: "Build All"
on:
  push:
    paths:
      - .github/workflows/build_all.yml
  pull_request:
    paths:
      - .github/workflows/build_all.yml

jobs:
  #  build_robotmk:
  #    uses: SoloJacobs/test_ci/.github/workflows/robotmk.yml@main
  #  build_rcc:
  #    uses: SoloJacobs/test_ci/.github/workflows/rcc.yml@main
  build_collector:
    uses: SoloJacobs/test_ci/.github/workflows/robotmk_collector.yml@main
  release:
    runs-on: ubuntu-latest
    needs: [build_collector] #, build_rcc, build_robotmk]
    steps:
      - name: "Download All"
        uses: actions/download-artifact@v3

      - name: "DEBUG"
        run: find .

      - name: "Update Release"
        uses: ncipollo/release-action@v1.13.0
        with:
          name: "Daily Build"
          allowUpdates: true
          artifacts: "./artifact/robotmk_collector.ps1"
          replacesArtifacts: true
          removeArtifacts: true
          prerelease: true
          artifactErrorsFailBuild: true
          updateOnlyUnreleased: true
          makeLatest: false
