---
name: "Build All"
on:
  push:
    paths:
      - .github/workflows/build_all.yml
  pull_request:
    paths:
      - .github/workflows/build_all.yml

jobs:
  build_robotmk:
    uses: elabit/robotmk/.github/workflows/robotmk.yml@main
  build_rcc:
    uses: elabit/robotmk/.github/workflows/rcc.yml@main
  release:
    runs-on: ubuntu-latest
    needs: [build_rcc, build_robotmk]
    steps:
      - name: "Download All"
        uses: actions/download-artifact@v3

      - name: "Show Available Artifacts"
        run: find . -type f

      - name: "Zip Artifacts"
        run: zip -r executables.zip artifact

      - name: "Update Release"
        uses: ncipollo/release-action@v1.13.0
        with:
          name: "Daily Build"
          allowUpdates: true
          artifacts: "executables.zip"
          replacesArtifacts: true
          removeArtifacts: true
          prerelease: true
          artifactErrorsFailBuild: true
          updateOnlyUnreleased: true
          makeLatest: false
