---
name: "QEMU"
on:
  workflow_dispatch:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - run: strace -e open,close,read,write,unlink,mkdir,rmdir -f docker run --privileged --rm tonistiigi/binfmt --install arm64
      - run: sudo find -name '*qemu*' /
