---
name: "QEMU"
on:
  workflow_dispatch:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - run: sudo find /
      - run: docker run --privileged --rm tonistiigi/binfmt --install arm64
      - run: sudo find /
