---
name: "QEMU"
on:
  workflow_dispatch:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - run: docker run --privileged --rm tonistiigi/binfmt --install arm64
      - run: /proc/sys/fs/binfmt_misc/qemu-aarch64 --help
      - run: /proc/sys/fs/binfmt_misc/qemu --help
