---
name: "RCC"

on:
  push:
    paths:
    - .github/workflows/rcc.yml
  pull_request:
    paths:
    - .github/workflows/rcc.yml
  workflow_call: {}

jobs:
  build_rcc_from_source:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
      with:
        repository: robocorp/rcc
        ref: v14.15.4
        path: rcc

    - name: "Setup Go"
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.x'

    - name: "Setup Rake"
      uses: ruby/setup-ruby@v1
      with:
          ruby-version: '2.7'

    - name: "Build RCC"
      working-directory: rcc
      run: rake build

    - name: "Test RCC"
      working-directory: rcc
      run: rake test

    - name: "Upload Artifact"
      uses: actions/upload-artifact@v3
      with:
        path: rcc/build
        if-no-files-found: error
