---
name: "RCC"

on:
  push:
    paths:
    - .github/workflows/rcc.yml
  pull_request:
    paths:
    - .github/workflows/rcc.yml
  workflow_call: {}

jobs:
  build_rcc_from_source:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
      with:
        repository: robocorp/rcc
        ref: v14.15.4
        path: rcc

    - name: "Setup Rake"
      run: |
        sudo apt-get install rubygems
        sudo gem install rake

    - name: "Setup Go"
      run: |
        wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
        # rcc expects $HOME/go/bin to be present (hard-coded)
        tar -C $HOME -xzf go1.21.0.linux-amd64.tar.gz
        echo "PATH=$PATH:$HOME/go/bin" >> $GITHUB_ENV

    - name: "Build RCC"
      run: rake -C rcc build

    - name: "Test RCC"
      run: rake -C rcc test

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: rcc.exe
        path: rcc/build
