---
name: Move v2-daily-build
on:
  schedule:
    # - cron: '0 2 * * *' # run at 2 AM UTC
    - cron: '* * * * *' # run at 2 AM UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git pull --tags -f
          git tag -f v2-daily-build
          git push --tags -f
