---
name: "Robotmk Collector"
on:
  push:
    paths:
    - .github/workflows/robotmk_collector.yml
  pull_request:
    paths:
    - .github/workflows/robotmk_collector.yml
  workflow_call: {}

jobs:
  build_robotmk_collector:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
      with:
        repository: elabit/robotmk
        ref: 610122edc937bfd74c4879cc85df365c9db437aa
        path: robotmk

    - name: "Upload Artifact"
      uses: actions/upload-artifact@v3
      with:
        path: robotmk/checkmk_extensions/agent
        if-no-files-found: error
