---
name: "Robotmk"
on:
  push:
    paths:
    - .github/workflows/robotmk.yaml
  pull_request:
    paths:
    - .github/workflows/robotmk.yaml

jobs:
  build_robotmk_from_source:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: elabit/robotmk
          ref: 610122edc937bfd74c4879cc85df365c9db437aa
          path: robotmk

      - name: "Setup Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          target: x86_64-pc-windows-gnu

      - name: Install MinGW-w64
        run: sudo apt-get install -y mingw-w64

      - name: "Build"
        working-directory: robotmk/v2/rust/
        run: cargo build --target=x86_64-pc-windows-gnu --release




            #create-release:
            #      - name: Update Release
            #        uses: ncipollo/release-action@v1.13.0
            #        with:
            #          name: Daily Build
            #          allowUpdates: true
            #          artifacts: LICENSE
            #          replacesArtifacts: true
            #          removeArtifacts: true
            #          prerelease: true
            #          artifactErrorsFailBuild: true
            #          updateOnlyUnreleased: true
            #          makeLatest: false
