---
name: "Robotmk"
on:
  push:
    paths:
    - .github/workflows/robotmk.yml
  pull_request:
    paths:
    - .github/workflows/robotmk.yml
  workflow_call: {}

jobs:
  build_robotmk_from_source:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          repository: elabit/robotmk
          ref: 610122edc937bfd74c4879cc85df365c9db437aa
          path: robotmk

      - name: "Setup Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          target: x86_64-pc-windows-gnu

      - name: "Install MinGW-w64"
        run: sudo apt-get install -y mingw-w64

      - name: "Build Robotmk"
        working-directory: robotmk/v2/rust/
        run: cargo build --target=x86_64-pc-windows-gnu --release
          #      - name: 'Upload Artifact'
          #        working-directory: robotmk/v2/rust/
          #        uses: actions/upload-artifact@v3
          #        with:
          #          name: robotmk.exe
          #          path: target/x86_64-pc-windows-gnu/release/robotmk.exe
