---
name: "Rust"
on:
  push:
    tags:
      - "v1.0.*"

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Install MinGW-w64
        run: sudo apt-get install -y mingw-w64

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Setup Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          target: x86_64-pc-windows-gnu

      - name: "Build"
        run: cargo build --target=x86_64-pc-windows-gnu

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: test_ci_binary
          path: target/x86_64-pc-windows-gnu/debug/test_ci.exe

      - name: Update Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: target/x86_64-pc-windows-gnu/debug/test_ci.exe
          artifactErrorsFailBuild: true
